//
//  DetailWorkerTests.swift
//  CleanFlickr
//
//  Created by Bhabani on 28/12/2018.
//  Copyright (c) 2018 Bhabani. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanFlickr
import XCTest

class DetailWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: DetailWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupDetailWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupDetailWorker() {
        sut = DetailWorker()
    }
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
